name: Build

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:

permissions:
  contents: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.version.outputs.version }}
      is-new-version: ${{ !fromJSON(steps.needs-release.outputs.exists || 'true') }}

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build -c Release --no-restore
    - name: Get Version
      id: version
      run: |
        VERSION=$(dotnet build Directory.Build.props -getProperty:Version)
        echo Version is $VERSION
        echo "version=$VERSION" >> $GITHUB_OUTPUT
    - name: Upload build artifact
      uses: actions/upload-artifact@v4
      with:
        name: ItemChanger.Silksong
        path: ItemChanger.Silksong/bin/Publish/*.zip
    - name: Check if release needed
      id: needs-release
      uses: mukunku/tag-exists-action@v1.6.0
      if: github.event_name == 'push'
      with:
        tag: v${{ steps.version.outputs.version }}

  release-github:
    needs:
      - build
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && needs.build.outputs.is-new-version == 'true'

    steps:
    - name: Download artifact
      uses: actions/download-artifact@v4
      with:
        name: ItemChanger.Silksong
        path: dist/
    - name: Release
      uses: softprops/action-gh-release@v2
      with:
        draft: false
        generate_release_notes: true
        fail_on_unmatched_files: true
        tag_name: v${{ needs.build.outputs.version }}
        files: |
          dist/*.zip
