name: Docs

on:
  release:
    types: [published]
  workflow_dispatch:

permissions:
  actions: read
  pages: write
  id-token: write

concurrency:
  group: pages
  cancel-in-progress: false

jobs:
  generate-docs:
    runs-on: ubuntu-latest

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '10.x'

      - name: Build Project
        run: dotnet build ItemChanger.Silksong/ItemChanger.Silksong.csproj -c Release
        continue-on-error: true

      - name: DocFX build
        working-directory: docs
        run: dnx -y docfx docfx.json

      - name: Upload assets
        uses: actions/upload-pages-artifact@v3
        with:
          path: docs/_site

      - name: Deploy
        id: deployment
        uses: actions/deploy-pages@v4
